In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## DATA COLUMNS DESCRIPTION

*   MSSubClass: Identifies the type of dwelling involved in the sale.
*   MSZoning: Identifies the general zoning classification of the sale.
*   LotFrontage: Linear feet of street connected to property 
*   LotArea: Lot size in square feet
*   Street: Type of road access to property
*   Alley: Type of alley access to property
*   LotShape: General shape of property
*   LandContour: Flatness of the property
*   Utilities: Type of utilities available
*   LotConfig: Lot configuration
*   LandSlope: Slope of property
*   Neighborhood: Physical locations within Ames city limits
*   Condition1: Proximity to various conditions
*   Condition2: Proximity to various conditions (if more than one is present)
*   BldgType: Type of dwelling
*   HouseStyle: Style of dwelling
*   OverallQual: Rates the overall material and finish of the house
*   OverallCond: Rates the overall condition of the house
*   YearBuilt: Original construction date
*   YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)
*   RoofStyle: Type of roof
*   RoofMatl: Roof material
*   Exterior1st: Exterior covering on house
*   Exterior2nd: Exterior covering on house (if more than one material)
*   MasVnrType: Masonry veneer type
*   MasVnrArea: Masonry veneer area in square feet
*   ExterQual: Evaluates the quality of the material on the exterior
*   ExterCond: Evaluates the present condition of the material on the exterior
*   Foundation: Type of foundation
*   BsmtQual: Evaluates the height of the basement
*   BsmtCond: Evaluates the general condition of the basement
*   BsmtExposure: Refers to walkout or garden level walls
*   BsmtFinType1: Rating of basement finished area
*   BsmtFinSF1: Type 1 finished square feet
*   BsmtFinType2: Rating of basement finished area (if multiple types)
*   BsmtFinSF2: Type 2 finished square feet
*   BsmtUnfSF: Unfinished square feet of basement area
*   TotalBsmtSF: Total square feet of basement area
*   Heating: Type of heating
*   HeatingQC: Heating quality and condition
*   CentralAir: Central air conditioning
*   Electrical: Electrical system
*   1stFlrSF: First Floor square feet
*   2ndFlrSF: Second floor square feet
*   LowQualFinSF: Low quality finished square feet (all floors)
*   GrLivArea: Above grade (ground) living area square feet
*   BsmtFullBath: Basement full bathrooms
*   BsmtHalfBath: Basement half bathrooms
*   FullBath: Full bathrooms above grade
*   HalfBath: Half baths above grade
*   Bedroom: Bedrooms above grade (does NOT include basement bedrooms)
*   Kitchen: Kitchens above grade
*   KitchenQual: Kitchen quality
*   TotRmsAbvGrd: Total rooms above grade (does not include bathrooms)
*   Functional: Home functionality (Assume typical unless deductions are warranted)
*   Fireplaces: Number of fireplaces
*   FireplaceQu: Fireplace quality
*   GarageType: Garage location
*   GarageYrBlt: Year garage was built
*   GarageFinish: Interior finish of the garage
*   GarageCars: Size of garage in car capacity
*   GarageArea: Size of garage in square feet
*   GarageQual: Garage quality
*   GarageCond: Garage condition
*   PavedDrive: Paved driveway
*   WoodDeckSF: Wood deck area in square feet
*   OpenPorchSF: Open porch area in square feet
*   EnclosedPorch: Enclosed porch area in square feet
*   3SsnPorch: Three season porch area in square feet
*   ScreenPorch: Screen porch area in square feet
*   PoolArea: Pool area in square feet
*   PoolQC: Pool quality
*   Fence: Fence quality
*   MiscFeature: Miscellaneous feature not covered in other categories
*   MiscVal: Value of miscellaneous feature
*   MoSold: Month Sold (MM)
*   YrSold: Year Sold (YYYY)
*   SaleType: Type of sale
*   SaleCondition: Condition of sale

In [2]:
dataset = pd.read_csv('HousingData.csv')

In [3]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,Unnamed: 80
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,NaN
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,NaN
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,NaN
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,NaN
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,1,2010,WD,Normal,NaN

In [4]:
# Data Quality Report
dataset.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,Unnamed: 80
count,2919.000000,2919.000000,2433.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2896.000000,2918.000000,...,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,1460.000000
mean,2920.000000,57.137718,69.305795,10168.114080,6.089072,5.564577,1971.312778,1984.264474,102.201312,441.423235,...,93.709832,47.486811,23.098321,2.602261,16.062350,2.251799,50.825968,6.213087,2007.792737,180921.195890
std,842.787043,42.517628,23.344905,7886.996359,1.409947,1.113131,30.291442,20.894344,179.334253,455.610826,...,126.526589,67.575493,64.244246,25.188169,56.184365,35.663946,567.402211,2.714762,1.314964,79442.502883
min,1461.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,2190.500000,20.000000,59.000000,7478.000000,5.000000,5.000000,1953.500000,1965.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129975.000000
50%,2920.000000,50.000000,68.000000,9453.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,368.500000,...,0.000000,26.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,3649.500000,70.000000,80.000000,11570.000000,7.000000,6.000000,2001.000000,2004.000000,164.000000,733.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,4379.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000

In [5]:
null_analysis = {}
for i in dataset.columns:
    data = dataset[i]
    null_analysis[i] = len(data[data.isna()==True])/len(dataset[i])
null_analysis

{'Id': 0.0,
 'MSSubClass': 0.0,
 'MSZoning': 0.0013703323055841042,
 'LotFrontage': 0.16649537512846865,
 'LotArea': 0.0,
 'Street': 0.0,
 'Alley': 0.9321685508735869,
 'LotShape': 0.0,
 'LandContour': 0.0,
 'Utilities': 0.0006851661527920521,
 'LotConfig': 0.0,
 'LandSlope': 0.0,
 'Neighborhood': 0.0,
 'Condition1': 0.0,
 'Condition2': 0.0,
 'BldgType': 0.0,
 'HouseStyle': 0.0,
 'OverallQual': 0.0,
 'OverallCond': 0.0,
 'YearBuilt': 0.0,
 'YearRemodAdd': 0.0,
 'RoofStyle': 0.0,
 'RoofMatl': 0.0,
 'Exterior1st': 0.00034258307639602604,
 'Exterior2nd': 0.00034258307639602604,
 'MasVnrType': 0.008221993833504625,
 'MasVnrArea': 0.0078794107571086,
 'ExterQual': 0.0,
 'ExterCond': 0.0,
 'Foundation': 0.0,
 'BsmtQual': 0.02774922918807811,
 'BsmtCond': 0.028091812264474134,
 'BsmtExposure': 0.028091812264474134,
 'BsmtFinType1': 0.027064063035286058,
 'BsmtFinSF1': 0.00034258307639602604,
 'BsmtFinType2': 0.027406646111682084,
 'BsmtFinSF2': 0.00034258307639602604,
 'BsmtUnfSF': 0.00034258307639602604,
 'TotalBsmtSF': 0.00034258307639602604,
 'Heating': 0.0,
 'HeatingQC': 0.0,
 'CentralAir': 0.0,
 'Electrical': 0.00034258307639602604,
 '1stFlrSF': 0.0,
 '2ndFlrSF': 0.0,
 'LowQualFinSF': 0.0,
 'GrLivArea': 0.0,
 'BsmtFullBath': 0.0006851661527920521,
 'BsmtHalfBath': 0.0006851661527920521,
 'FullBath': 0.0,
 'HalfBath': 0.0,
 'BedroomAbvGr': 0.0,
 'KitchenAbvGr': 0.0,
 'KitchenQual': 0.00034258307639602604,
 'TotRmsAbvGrd': 0.0,
 'Functional': 0.0006851661527920521,
 'Fireplaces': 0.0,
 'FireplaceQu': 0.48646796848235696,
 'GarageType': 0.05378554299417609,
 'GarageYrBlt': 0.05447070914696814,
 'GarageFinish': 0.05447070914696814,
 'GarageCars': 0.00034258307639602604,
 'GarageArea': 0.00034258307639602604,
 'GarageQual': 0.05447070914696814,
 'GarageCond': 0.05447070914696814,
 'PavedDrive': 0.0,
 'WoodDeckSF': 0.0,
 'OpenPorchSF': 0.0,
 'EnclosedPorch': 0.0,
 '3SsnPorch': 0.0,
 'ScreenPorch': 0.0,
 'PoolArea': 0.0,
 'PoolQC': 0.9965741692360397,
 'Fence': 0.8043850633778691,
 'MiscFeature': 0.9640287769784173,
 'MiscVal': 0.0,
 'MoSold': 0.0,
 'YrSold': 0.0,
 'SaleType': 0.00034258307639602604,
 'SaleCondition': 0.0,
 'Unnamed: 80': 0.499828708461802}

In [6]:
# finding names of columns where null values are greater than 60 percent
for i in dataset.columns:
    if null_analysis[i]>0.6:
        print(i)

Alley
PoolQC
Fence
MiscFeature

In [7]:
# removing these columns
dataset = dataset.drop(['Alley','PoolQC','Fence','MiscFeature'],axis = 1)

In [8]:
# checking significant remaining null values
for i in dataset.columns:
    if null_analysis[i]>0.4:
        print(i)

FireplaceQu
Unnamed: 80

In [9]:
# removing these also
dataset = dataset.drop(['FireplaceQu','Unnamed: 80'],axis = 1)

In [10]:
# checking for cardinality
for i in dataset.columns:
    print('column name :{0} datatype : {1}  cardinality : {2} '.format(i,type(dataset[i][0]),len(dataset[i].unique())))

column name :Id datatype : <class 'numpy.int64'>  cardinality : 2919
column name :MSSubClass datatype : <class 'numpy.int64'>  cardinality : 16
column name :MSZoning datatype : <class 'str'>  cardinality : 6
column name :LotFrontage datatype : <class 'numpy.float64'>  cardinality : 129
column name :LotArea datatype : <class 'numpy.int64'>  cardinality : 1951
column name :Street datatype : <class 'str'>  cardinality : 2
column name :LotShape datatype : <class 'str'>  cardinality : 4
column name :LandContour datatype : <class 'str'>  cardinality : 4
column name :Utilities datatype : <class 'str'>  cardinality : 3
column name :LotConfig datatype : <class 'str'>  cardinality : 5
column name :LandSlope datatype : <class 'str'>  cardinality : 3
column name :Neighborhood datatype : <class 'str'>  cardinality : 25
column name :Condition1 datatype : <class 'str'>  cardinality : 9
column name :Condition2 datatype : <class 'str'>  cardinality : 8
column name :BldgType datatype : <class 'str'>  cardinality : 5
column name :HouseStyle datatype : <class 'str'>  cardinality : 8
column name :OverallQual datatype : <class 'numpy.int64'>  cardinality : 10
column name :OverallCond datatype : <class 'numpy.int64'>  cardinality : 9
column name :YearBuilt datatype : <class 'numpy.int64'>  cardinality : 118
column name :YearRemodAdd datatype : <class 'numpy.int64'>  cardinality : 61
column name :RoofStyle datatype : <class 'str'>  cardinality : 6
column name :RoofMatl datatype : <class 'str'>  cardinality : 8
column name :Exterior1st datatype : <class 'str'>  cardinality : 16
column name :Exterior2nd datatype : <class 'str'>  cardinality : 17
column name :MasVnrType datatype : <class 'str'>  cardinality : 5
column name :MasVnrArea datatype : <class 'numpy.float64'>  cardinality : 445
column name :ExterQual datatype : <class 'str'>  cardinality : 4
column name :ExterCond datatype : <class 'str'>  cardinality : 5
column name :Foundation datatype : <class 'str'>  cardinality : 6
column name :BsmtQual datatype : <class 'str'>  cardinality : 5
column name :BsmtCond datatype : <class 'str'>  cardinality : 5
column name :BsmtExposure datatype : <class 'str'>  cardinality : 5
column name :BsmtFinType1 datatype : <class 'str'>  cardinality : 7
column name :BsmtFinSF1 datatype : <class 'numpy.float64'>  cardinality : 992
column name :BsmtFinType2 datatype : <class 'str'>  cardinality : 7
column name :BsmtFinSF2 datatype : <class 'numpy.float64'>  cardinality : 273
column name :BsmtUnfSF datatype : <class 'numpy.float64'>  cardinality : 1136
column name :TotalBsmtSF datatype : <class 'numpy.float64'>  cardinality : 1059
column name :Heating datatype : <class 'str'>  cardinality : 6
column name :HeatingQC datatype : <class 'str'>  cardinality : 5
column name :CentralAir datatype : <class 'str'>  cardinality : 2
column name :Electrical datatype : <class 'str'>  cardinality : 6
column name :1stFlrSF datatype : <class 'numpy.int64'>  cardinality : 1083
column name :2ndFlrSF datatype : <class 'numpy.int64'>  cardinality : 635
column name :LowQualFinSF datatype : <class 'numpy.int64'>  cardinality : 36
column name :GrLivArea datatype : <class 'numpy.int64'>  cardinality : 1292
column name :BsmtFullBath datatype : <class 'numpy.float64'>  cardinality : 5
column name :BsmtHalfBath datatype : <class 'numpy.float64'>  cardinality : 4
column name :FullBath datatype : <class 'numpy.int64'>  cardinality : 5
column name :HalfBath datatype : <class 'numpy.int64'>  cardinality : 3
column name :BedroomAbvGr datatype : <class 'numpy.int64'>  cardinality : 8
column name :KitchenAbvGr datatype : <class 'numpy.int64'>  cardinality : 4
column name :KitchenQual datatype : <class 'str'>  cardinality : 5
column name :TotRmsAbvGrd datatype : <class 'numpy.int64'>  cardinality : 14
column name :Functional datatype : <class 'str'>  cardinality : 8
column name :Fireplaces datatype : <class 'numpy.int64'>  cardinality : 5
column name :GarageType datatype : <class 'str'>  cardinality : 7
column name :GarageYrBlt datatype : <class 'numpy.float64'>  cardinality : 104
column name :GarageFinish datatype : <class 'str'>  cardinality : 4
column name :GarageCars datatype : <class 'numpy.float64'>  cardinality : 7
column name :GarageArea datatype : <class 'numpy.float64'>  cardinality : 604
column name :GarageQual datatype : <class 'str'>  cardinality : 6
column name :GarageCond datatype : <class 'str'>  cardinality : 6
column name :PavedDrive datatype : <class 'str'>  cardinality : 3
column name :WoodDeckSF datatype : <class 'numpy.int64'>  cardinality : 379
column name :OpenPorchSF datatype : <class 'numpy.int64'>  cardinality : 252
column name :EnclosedPorch datatype : <class 'numpy.int64'>  cardinality : 183
column name :3SsnPorch datatype : <class 'numpy.int64'>  cardinality : 31
column name :ScreenPorch datatype : <class 'numpy.int64'>  cardinality : 121
column name :PoolArea datatype : <class 'numpy.int64'>  cardinality : 14
column name :MiscVal datatype : <class 'numpy.int64'>  cardinality : 38
column name :MoSold datatype : <class 'numpy.int64'>  cardinality : 12
column name :YrSold datatype : <class 'numpy.int64'>  cardinality : 5
column name :SaleType datatype : <class 'str'>  cardinality : 10
column name :SaleCondition datatype : <class 'str'>  cardinality : 6

In [23]:
for i in dataset.columns:
    if isinstance(dataset[i][0],float):
        print("continuous column name is {0} with unique percentage {1} ".format(i,len(dataset[i].unique())/len(dataset[i])))

continuous column name is LotFrontage with unique percentage 0.044193216855087356
continuous column name is MasVnrArea with unique percentage 0.15244946899623157
continuous column name is BsmtFinSF1 with unique percentage 0.3398424117848578
continuous column name is BsmtFinSF2 with unique percentage 0.09352517985611511
continuous column name is BsmtUnfSF with unique percentage 0.38917437478588557
continuous column name is TotalBsmtSF with unique percentage 0.36279547790339156
continuous column name is BsmtFullBath with unique percentage 0.0017129153819801302
continuous column name is BsmtHalfBath with unique percentage 0.0013703323055841042
continuous column name is GarageYrBlt with unique percentage 0.03562863994518671
continuous column name is GarageCars with unique percentage 0.002398081534772182
continuous column name is GarageArea with unique percentage 0.2069201781431997

In [29]:
# dropping columns with less than 1 percent unique values for continuous columns
dataset = dataset.drop([i for i in dataset.columns if len(dataset[i].unique())/len(dataset[i]) > 0.1],axis = 1)